#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-build
Version  : 1
Release  : 1
URL      : file:///aot/build/clearlinux/packages/python-build/python-build-1.tar.gz
Source0  : file:///aot/build/clearlinux/packages/python-build/python-build-1.tar.gz
Summary  : Tool to download and build python based upon pyenv.
Group    : Development/Tools
License  : GPL-2.0
Requires: python-build-bin = %{version}-%{release}
Requires: python-build-python = %{version}-%{release}
Requires: python-build-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pep517
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-build
BuildRequires : tox
BuildRequires : virtualenv

%description
# build
[![CI](https://github.com/pypa/build/workflows/check/badge.svg)](https://github.com/pypa/build/actions)
[![codecov](https://codecov.io/gh/pypa/build/branch/main/graph/badge.svg)](https://codecov.io/gh/pypa/build)
[![Documentation Status](https://readthedocs.org/projects/pypa-build/badge/?version=latest)](https://pypa-build.readthedocs.io/en/latest/?badge=latest)
[![PyPI version](https://badge.fury.io/py/build.svg)](https://pypi.org/project/build/)
[![Discord](https://img.shields.io/discord/803025117553754132?label=Discord%20chat%20%23build&style=flat-square)](https://discord.gg/pypa)

%package bin
Summary: bin components for the python-build package.
Group: Binaries

%description bin
bin components for the python-build package.


%package python
Summary: python components for the python-build package.
Group: Default
Requires: python-build-python3 = %{version}-%{release}

%description python
python components for the python-build package.


%package python3
Summary: python3 components for the python-build package.
Group: Default
Requires: python3-core
Provides: pypi(python_build)

%description python3
python3 components for the python-build package.


%prep
%setup -q -n python-build
cd %{_builddir}/python-build

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1620016744
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=16 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=16 "
export MAKEFLAGS=%{?_smp_mflags}
if [ ! -f setup.py ]; then
python3 -m build
else
python3 setup.py build
fi
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
if [ ! -f setup.py ]; then
python3 -m build  install --root=%{buildroot}
else
python3 -tt setup.py build  install --root=%{buildroot}
fi
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pyproject-build

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
